services:
  journey_postgres:
    image: postgres:16
    container_name: journey_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    networks:
      - tools_default-network

  journey_mailpit:
    image: axllent/mailpit:latest
    container_name: journey_mailpit
    ports:
      - 1024:1024
      - 8025:8025

networks:
  tools_default-network:
    external: true
